name: placeSMP
version: '${project.version}'
main: net.shieldbreak.placesmp.Main
api-version: 1.19
commands:
  credits:
  discord:
  web:
    aliases:
      - website
  place:
  smp:
  canvas:
    aliases:
      - map
  rtp:
    aliases:
      - randomtp
      - randomteleport
  toggleworlds: